export const GET_TODOS_SUCCESS = "GET_TODOS_SUCCESS";
export const GET_TODOS_FAILED = "GET_TODOS_FAILED";

export const ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS";
export const ADD_TODO_FAILED = "ADD_TODO_FAILED";

export const EDIT_TODO_TITLE_SUCCESS = "EDIT_TODO_TITLE_SUCCESS";
export const EDIT_TODO_TITLE_FAILED = "EDIT_TODO_TITLE_FAILED";

export const EDIT_CHECKED_TODO_SUCCESS = "EDIT_CHECKED_TODO_SUCCESS";
export const EDIT_CHECKED_TODO_FAILED = "EDIT_CHECKED_TODO_FAILED";

export const DELETE_TODO_SUCCESS = "DELETE_TODO_SUCCESS";
export const DELETE_TODO_FAILED = "DELETE_TODO_FAILED";
